Repository IgniteUI/app-builder-docfx, pull requests merged in 2021-12, with the labels that each got.

#6 chore(images): add missing seo banner image
  en/images/marketing/ignite-ui--cta-banner-2.png
Labels: bug

#12 Promote changelog updates
  en/change-log.md
Labels: status: pending-localization

#14 Updating JA changelog - vnext
  jp/change-log.md
Labels: status: localized

#15 Add framework buttons -vnext
  en/global.json
  jp/global.json
  package-lock.json
  package.json
Labels: awaiting-test

#16 Add framework buttons -master
  en/global.json
  jp/global.json
  package-lock.json
  package.json
Labels: verified
