Repository IgniteUI/app-builder-docfx, pull requests merged in 2022-03, with the labels that each got.

#46 docs: use question icon instead of check for partially generated components
  en/blazor-support.md
  en/generate-app/generate-app-overview.md
Labels: documentation, status: pending-localization

#48 [JA] Updating Blazor Support and Generating App topics
  jp/blazor-support.md
  jp/generate-app/generate-app-overview.md
Labels: status: localized, status: verified

#45 Add topics for Swagger and On-prem
  en/getting-started.md
  en/images/activate-app-builder.png
  en/images/configure-endpoints.PNG
  en/images/docker-apps.png
  en/images/endpoint-params.PNG
  en/images/endpoints-dialog.png
  en/images/login-parameters.png
  en/images/on-prem-ab-demo.gif
  en/images/on-premise-sql-express.png
  en/images/sql-server-config-manager.png
  en/images/swagger-demo-original.gif
  en/on-prem-prerequisites-and-installation.md
  en/running-desktop-app.md
  en/sidebar-toc/toc.yml
  en/using-data-in-your-app.md
Labels: verified

#52 Promote Staging to Production
  en/app-themes/app-themes.md
  en/blazor-support.md
  en/change-log.md
  en/flex-layouts/flex-layouts.md
  en/generate-app/generate-app-overview.md
  en/generate-app/run-application-locally.md
  en/generate-app/upload-application-to-github.md
  en/getting-started.md
  en/images/activate-app-builder.png
  en/images/configure-endpoints.PNG
  en/images/docker-apps.png
  en/images/endpoint-params.PNG
  en/images/endpoints-dialog.png
  en/images/login-parameters.png
  en/images/on-prem-ab-demo.gif
  en/images/on-premise-sql-express.png
  en/images/sql-server-config-manager.png
  en/images/swagger-demo-original.gif
  en/indigo-design-app-builder-components.md
  en/interactions.md
  en/interface-overview.md
  en/on-prem-prerequisites-and-installation.md
  en/open-api-swagger-support.md
  en/preview-code.md
  en/running-desktop-app.md
  en/sidebar-toc/toc.yml
  en/single-page-apps-and-navigation.md
  en/using-data-in-your-app.md
  jp/blazor-support.md
  jp/generate-app/generate-app-overview.md
Labels: status: verified

#58 [Localization] March Release Changes
  jp/app-themes/app-themes.md
  jp/blazor-support.md
  jp/change-log.md
  jp/flex-layouts/flex-layouts.md
  jp/generate-app/generate-app-overview.md
  jp/generate-app/run-application-locally.md
  jp/generate-app/upload-application-to-github.md
  jp/getting-started.md
  jp/images/activate-app-builder.png
  jp/images/configure-endpoints.PNG
  jp/images/docker-apps.png
  jp/images/endpoint-params.PNG
  jp/images/endpoints-dialog.png
  jp/images/login-parameters.png
  jp/images/on-prem-ab-demo.gif
  jp/images/on-premise-sql-express.png
  jp/images/sql-server-config-manager.png
  jp/images/swagger-demo-original.gif
  jp/indigo-design-app-builder-components.md
  jp/interactions.md
  jp/interface-overview.md
  jp/on-prem-prerequisites-and-installation.md
  jp/open-api-swagger-support.md
  jp/preview-code.md
  jp/running-desktop-app.md
  jp/sidebar-toc/toc.yml
  jp/single-page-apps-and-navigation.md
  jp/using-data-in-your-app.md
Labels: status: localized, status: verified

#55 Update Blazor limitations
  en/blazor-support.md
Labels: documentation, status: pending-localization

#61 Update Blazor components limitations
  en/blazor-support.md
  en/generate-app/generate-app-overview.md
Labels: documentation, status: pending-localization, status: in-test
