Repository IgniteUI/app-builder-docfx, pull requests merged in 2022-04, with the labels that each got.

#68 add tutorial video for getting-started
  en/getting-started.md
Labels: awaiting-test

#70 add tutorial video for getting-started
  en/getting-started.md
  jp/getting-started.md
Labels: status: pending-localization, awaiting-test

#73 Update april release
  en/change-log.md
  jp/change-log.md
Labels: status: localized

#72 [Localization] Updating topics with the latest changes
  jp/generate-app/upload-application-to-github.md
  jp/getting-started.md
Labels: status: localized, status: verified

#74 [JA] Changelog fixes - master
  en/change-log.md
  jp/change-log.md
  jp/getting-started.md
Labels: status: localized
