Repository IgniteUI/app-builder-docfx, pull requests merged in 2022-12, with the labels that each got.

#111 New topics for the UI Kits
  en/change-log.md
  en/design-to-code-story.md
  en/docfx.json
  en/images/download-project.png
  en/images/ui-kits/figma/1.png
  en/images/ui-kits/figma/2.png
  en/images/ui-kits/figma/3.png
  en/images/ui-kits/figma/4.png
  en/images/ui-kits/figma/5.png
  en/images/ui-kits/figma/6.png
  en/images/ui-kits/figma/7.png
  en/images/ui-kits/figma/8.png
  en/sidebar-toc/toc.yml
  en/ui-kits/adobe-xd.md
  en/ui-kits/figma.md
  en/ui-kits/sketch.md
Labels: status: pending-localization

#113 Add more download assets urls
  en/design-to-code-story.md
  en/ui-kits/adobe-xd.md
  en/ui-kits/figma.md
  en/ui-kits/sketch.md
Labels: status: pending-localization

#115 Minor changes figma topic
  en/images/ui-kits/figma/8.png
  en/ui-kits/figma.md
Labels: status: pending-localization

#117 Localization UI kits
  jp/blazor-support.md
  jp/change-log.md
  jp/design-to-code-story.md
  jp/docfx.json
  jp/images/download-project.png
  jp/images/ui-kits/figma/1.png
  jp/images/ui-kits/figma/2.png
  jp/images/ui-kits/figma/3.png
  jp/images/ui-kits/figma/4.png
  jp/images/ui-kits/figma/5.png
  jp/images/ui-kits/figma/6.png
  jp/images/ui-kits/figma/7.png
  jp/images/ui-kits/figma/8.png
  jp/share-preview-edit-app.md
  jp/sidebar-toc/toc.yml
  jp/ui-kits/adobe-xd.md
  jp/ui-kits/figma.md
  jp/ui-kits/sketch.md
  jp/web-components-support.md
Labels: status: localized, status: verified

#119 Zkolev/update figma topic
  en/ui-kits/figma.md
Labels: status: pending-localization

#121 Update template version
  package-lock.json
  package.json
Labels: status: verified

#122 [JP] Updating Figma topic
  jp/ui-kits/figma.md
Labels: status: localized, status: verified
