Repository IgniteUI/app-builder-docfx, pull requests merged in 2022-06, with the labels that each got.

#79 Add local network sources support topic
  en/getting-started.md
  en/images/IIS-config.gif
  en/images/internal-network-data-source.gif
  en/images/request-failed-error.gif
  en/open-api-swagger-support.md
  en/sidebar-toc/toc.yml
  en/using-data-in-your-app.md
Labels: status: pending-localization

#81 Update seo cta banners -vnext
  en/images/marketing/app-builder-wysiwyg.gif
  jp/images/marketing/app-builder-wysiwyg.gif
  package-lock.json
  package.json
Labels: status: verified

#82 Update seo cta banners -master
  en/images/marketing/app-builder-wysiwyg.gif
  jp/images/marketing/app-builder-wysiwyg.gif
  package-lock.json
  package.json
Labels: awaiting-test

#83 [JA] Updating with latest changes
  jp/getting-started.md
  jp/images/IIS-config.gif
  jp/images/internal-network-data-source.gif
  jp/images/request-failed-error.gif
  jp/open-api-swagger-support.md
  jp/sidebar-toc/toc.yml
  jp/using-data-in-your-app.md
Labels: status: localized, verified

#86 [JP] Updating changelog, other changes - vNext
  jp/change-log.md
  jp/generate-app/upload-application-to-github.md
  jp/images/App-VSCode-Indigo-Design-App-Builder2.PNG
  jp/images/another-repository-linked.png
  jp/images/connect-to-github-@2x.png
  jp/images/create-new-repo-publish-to-github-@2x.png
  jp/images/gh-changes-not-yet-merged.PNG
  jp/images/gh-repository-linked-to-another-platform.PNG
  jp/images/pick-repository-publish-to-github-@2x.png
Labels: status: localized, status: verified
