Repository IgniteUI/app-builder-docfx, pull requests merged in 2022-09, with the labels that each got.

#95 update igniteui-docfx-template version
  package-lock.json
  package.json
Labels: verified

#98 Add jp cta banners - vnext
  jp/images/marketing/app-builder-wysiwyg.gif
  package-lock.json
  package.json
Labels: awaiting-test

#99 Add jp cta banners - master
  jp/images/marketing/app-builder-wysiwyg.gif
  package-lock.json
  package.json
Labels: verified

#101 Update to 3.3.2
  package-lock.json
  package.json
Labels: verified

#102 Update docfx-template to 3.3.2 master
  package-lock.json
  package.json
Labels: status: verified
