Repository IgniteUI/app-builder-docfx, pull requests merged in 2022-01, with the labels that each got.

#27 chore(linux-installer): update app image file info
  en/getting-started.md
  en/images/run-app-image.png
  en/running-desktop-app.md
  en/sidebar-toc/toc.yml
Labels: documentation, status: verified

#26 chore(linux-installer): update app image file info
  en/getting-started.md
  en/images/run-app-image.png
  en/running-desktop-app.md
  en/sidebar-toc/toc.yml
Labels: documentation, status: verified

#31 chore(installers): add link in getting started
  en/getting-started.md
  en/images/run-app-image.png
  en/running-desktop-app.md
  en/sidebar-toc/toc.yml
Labels: documentation, awaiting-test

#30 chore(installers): add link in getting started
  en/getting-started.md
  en/running-desktop-app.md
Labels: documentation

#32 [Localization] Adding the latest topic changes - Running the Desktop App
  jp/getting-started.md
  jp/images/run-app-image.png
  jp/running-desktop-app.md
  jp/sidebar-toc/toc.yml
Labels: status: localized, status: verified

#35 [Localization] [JP] Adding January release notes.
  jp/change-log.md
Labels: status: localized, status: verified
