Repository IgniteUI/app-builder-docfx, pull requests merged in 2023-03, with the labels that each got.

#139 [JP] Fixing Fluid Layout topic.
  jp/how-to/responsive-fluid-layout.md
Labels: documentation, status: localized

#143 Troubleshoot swagger grayed out
  en/images/using-data-in-your-app/openapi-endpoint-grayedout.png
  en/images/using-data-in-your-app/openapi-endpoint-noreponse.png
  en/images/using-data-in-your-app/openapi-endpoint-typed-reponse.png
  en/using-data-in-your-app.md
  jp/how-to/responsive-fluid-layout.md
Labels: status: pending-localization

#145 Update crud docs
  en/using-data-in-your-app/crud-operations.md
Labels: status: pending-localization

#146 [JP] Adding the latest topic changes
  jp/images/using-data-in-your-app/openapi-endpoint-grayedout.png
  jp/images/using-data-in-your-app/openapi-endpoint-noreponse.png
  jp/images/using-data-in-your-app/openapi-endpoint-typed-reponse.png
  jp/using-data-in-your-app.md
  jp/using-data-in-your-app/crud-operations.md
Labels: status: localized, status: verified

#144 Update image styles
  en/app-themes/app-themes.md
  en/blazor-support.md
  en/design-to-code-story.md
  en/flex-layouts/flex-layouts.md
  en/generate-app/generate-app-overview.md
  en/generate-app/run-application-locally.md
  en/generate-app/upload-application-to-github.md
  en/getting-started.md
  en/how-to/responsive-fluid-layout.md
  en/indigo-design-app-builder-components.md
  en/interactions.md
  en/interface-overview.md
  en/on-prem-prerequisites-and-installation.md
  en/open-api-swagger-support.md
  en/preview-code.md
  en/running-desktop-app.md
  en/share-preview-edit-app.md
  en/single-page-apps-and-navigation.md
  en/ui-kits/adobe-xd.md
  en/ui-kits/figma.md
  en/ui-kits/sketch.md
  en/using-data-in-your-app.md
  en/using-data-in-your-app/crud-operations.md
  en/web-components-support.md
  jp/app-themes/app-themes.md
  jp/blazor-support.md
  jp/design-to-code-story.md
  jp/flex-layouts/flex-layouts.md
  jp/generate-app/generate-app-overview.md
  jp/generate-app/run-application-locally.md
  jp/generate-app/upload-application-to-github.md
  jp/getting-started.md
  jp/how-to/responsive-fluid-layout.md
  jp/indigo-design-app-builder-components.md
  jp/interactions.md
  jp/interface-overview.md
  jp/on-prem-prerequisites-and-installation.md
  jp/open-api-swagger-support.md
  jp/preview-code.md
  jp/running-desktop-app.md
  jp/share-preview-edit-app.md
  jp/single-page-apps-and-navigation.md
  jp/ui-kits/adobe-xd.md
  jp/ui-kits/figma.md
  jp/ui-kits/sketch.md
  jp/using-data-in-your-app.md
  jp/using-data-in-your-app/crud-operations.md
  jp/web-components-support.md
  package-lock.json
  package.json
Labels: verified
