Repository IgniteUI/app-builder-docfx, pull requests merged in 2023-02, with the labels that each got.

#129 [JA] Updating on-prem and changelog
  jp/change-log.md
  jp/images/ui-kits/figma/app-ready.png
  jp/images/ui-kits/figma/code-review.png
  jp/images/ui-kits/figma/download-app.png
  jp/images/ui-kits/figma/figma-app-ready.png
  jp/on-prem-prerequisites-and-installation.md
Labels: status: localized, verified

#131 Add CRUD topic and hierarchical support for repeaters
  en/change-log.md
  en/getting-started.md
  en/images/on-premise-sql-express.png
  en/images/on-premises-sql-express.png
  en/images/using-data-in-your-app/CRUD.png
  en/images/using-data-in-your-app/Nested-Iterators.png
  en/images/using-data-in-your-app/Nested-Repeaters.gif
  en/images/using-data-in-your-app/Nested-Result.png
  en/images/using-data-in-your-app/adding-data-interaction.png
  en/images/using-data-in-your-app/nested-data-context-2.png
  en/images/using-data-in-your-app/nested-data-context-result.png
  en/images/using-data-in-your-app/nested-data-context.png
  en/images/using-data-in-your-app/swagger-customers-api.png
  en/images/using-data-in-your-app/turn-off-live-update.png
  en/images/using-data-in-your-app/want-to-make-any-changes-question.png
  en/on-prem-prerequisites-and-installation.md
  en/sidebar-toc/toc.yml
  en/using-data-in-your-app.md
  en/using-data-in-your-app/crud-operations.md
  jp/on-prem-prerequisites-and-installation.md
Labels: status: pending-localization

#132 [JP] February 2023 Release Updates
  jp/change-log.md
  jp/images/on-premise-sql-express.png
  jp/images/on-premises-sql-express.png
  jp/images/using-data-in-your-app/CRUD.png
  jp/images/using-data-in-your-app/Nested-Iterators.png
  jp/images/using-data-in-your-app/Nested-Repeaters.gif
  jp/images/using-data-in-your-app/Nested-Result.png
  jp/images/using-data-in-your-app/adding-data-interaction.png
  jp/images/using-data-in-your-app/nested-data-context-2.png
  jp/images/using-data-in-your-app/nested-data-context-result.png
  jp/images/using-data-in-your-app/nested-data-context.png
  jp/images/using-data-in-your-app/swagger-customers-api.png
  jp/images/using-data-in-your-app/turn-off-live-update.png
  jp/images/using-data-in-your-app/want-to-make-any-changes-question.png
  jp/sidebar-toc/toc.yml
  jp/using-data-in-your-app.md
  jp/using-data-in-your-app/crud-operations.md
Labels: status: localized, status: verified

#134 Responsive fluid layout
  en/change-log.md
  en/docfx.json
  en/how-to/responsive-fluid-layout.md
  en/images/how-to/basic-structure.png
  en/images/how-to/final-result.png
  en/images/how-to/step-1.png
  en/images/how-to/step-2.png
  en/images/how-to/step-3.png
  en/images/how-to/step-4.png
  en/images/how-to/step-5.png
  en/sidebar-toc/toc.yml
Labels: status: pending-localization

#136 [JP] Responsive Fluid Layout topic.
  jp/change-log.md
  jp/docfx.json
  jp/how-to/responsive-fluid-layout.md
  jp/images/how-to/basic-structure.png
  jp/images/how-to/final-result.png
  jp/images/how-to/step-1.png
  jp/images/how-to/step-2.png
  jp/images/how-to/step-3.png
  jp/images/how-to/step-4.png
  jp/images/how-to/step-5.png
  jp/sidebar-toc/toc.yml
Labels: status: localized, status: verified
