Repository IgniteUI/app-builder-docfx, pull requests merged in 2023-01, with the labels that each got.

#123 Promote production
  jp/ui-kits/figma.md
  package-lock.json
  package.json
Labels: awaiting-test

#124 Update template version
  package-lock.json
  package.json
Labels: verified

#125 Update On-prem topic
  en/change-log.md
  en/images/ui-kits/figma/app-ready.png
  en/images/ui-kits/figma/code-review.png
  en/images/ui-kits/figma/download-app.png
  en/images/ui-kits/figma/figma-app-ready.png
  en/on-prem-prerequisites-and-installation.md
Labels: status: pending-localization
