Repository IgniteUI/app-builder-docfx, pull requests merged in 2024-04, with the labels that each got.

#207 Update youtube videos and sitemap
  en/app-themes/app-themes.md
  en/docfx.json
  en/flex-layouts/flex-layouts.md
  en/getting-started.md
  en/global.json
  en/single-page-apps-and-navigation.md
  jp/app-themes/app-themes.md
  jp/docfx.json
  jp/flex-layouts/flex-layouts.md
  jp/getting-started.md
  jp/global.json
  jp/single-page-apps-and-navigation.md
  package-lock.json
  package.json
Labels: awaiting-test

#214 Updating JA for #205
  en/blazor-support.md
  en/getting-started.md
  en/indigo-design-app-builder-components.md
  en/interactions.md
  en/open-api-swagger-support.md
  en/single-page-apps-and-navigation.md
  jp/app-builder-overview.md
  jp/app-themes/app-themes.md
  jp/blazor-support.md
  jp/design-to-code-story.md
  jp/generate-app/generate-app-overview.md
  jp/generate-app/run-application-locally.md
  jp/generate-app/upload-application-to-github.md
  jp/getting-started.md
  jp/indigo-design-app-builder-components.md
  jp/interactions.md
  jp/interface-overview.md
  jp/open-api-swagger-support.md
  jp/preview-code.md
  jp/share-preview-edit-app.md
  jp/single-page-apps-and-navigation.md
  jp/ui-kits/figma.md
  jp/ui-kits/sketch.md
  jp/web-components-support.md
Labels: status: localized

#216 Update template and videos sizes
  en/app-themes/app-themes.md
  en/flex-layouts/flex-layouts.md
  en/getting-started.md
  en/single-page-apps-and-navigation.md
  jp/app-themes/app-themes.md
  jp/flex-layouts/flex-layouts.md
  jp/getting-started.md
  jp/single-page-apps-and-navigation.md
  package-lock.json
  package.json
Labels: verified
