Repository IgniteUI/app-builder-docfx, pull requests merged in 2024-02, with the labels that each got.

#193 Add help topic about the use of Route Parameters
  en/blazor-support.md
  en/guide-to-variables-in-app-builder/component-properties-binding.md
  en/guide-to-variables-in-app-builder/route-parameters-navigation.md
  en/guide-to-variables-in-app-builder/url-parameters-binding.md
  en/guide-to-variables-in-app-builder/variables-management.md
  en/guide-to-variables-in-app-builder/working-with-events-and-actions.md
  en/images/state-and-context/27-create-route-param.png
  en/images/state-and-context/28-create-navigate-to-action.png
  en/interactions.md
  en/master-detail/master-detail.md
  en/sidebar-toc/toc.yml
Labels: status: pending-localization, status: verified

#195 [JA] Route Parameters - new topic
  jp/blazor-support.md
  jp/guide-to-variables-in-app-builder/component-properties-binding.md
  jp/guide-to-variables-in-app-builder/route-parameters-navigation.md
  jp/guide-to-variables-in-app-builder/url-parameters-binding.md
  jp/guide-to-variables-in-app-builder/variables-management.md
  jp/guide-to-variables-in-app-builder/working-with-events-and-actions.md
  jp/images/state-and-context/27-create-route-param.png
  jp/images/state-and-context/28-create-navigate-to-action.png
  jp/interactions.md
  jp/master-detail/master-detail.md
  jp/sidebar-toc/toc.yml
Labels: status: localized

#197 chore(*): Changelog updates
  en/change-log.md
Labels: status: pending-localization

#201 [JA] February 2024 Release Notes
  jp/change-log.md
Labels: status: localized
